[package]
name = "rusty-book-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1.37", features = ["full"] }

[dev-dependencies]
futures = "0.3.31"
reqwest = "0.12.9"
rstest = "0.18"
