[package]
name = "sqlx-test-example"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
sqlx = { workspace = true, features = ["runtime-tokio", "postgres"] }

[dev-dependencies]
rstest = "0.23.0"
